import Navbar from "@/Components/layout/Navbar";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/layout/Footer";
import { AuthProvider } from "@/Components/layout/AuthContext";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { ToastContainer } from "react-toastify";
import { authClient } from "@/lib/auth-client";
import { api } from "@/lib/baseAPI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  const user = session?.user;
  
  const token = await auth.api.getToken({
      headers: await headers ()
  }); 


  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider user={user} token={token.token}  >
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
